Redis:
  tty: true
  image: redis:3
  volumes:
  - ${BCX_DIR}/redis:/data
  stdin_open: true
MySQL:
  environment:
    MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: 'bcx'
  tty: true
  image: mysql:5.6
  volumes:
  - ${BCX_DIR}/mysql:/var/lib/mysql
  stdin_open: true
PHPNginx:
  labels:
    io.rancher.sidekicks: Redis,MySQL,Mongo
  tty: true
  image: bridgeconx/ldock-phpnginx:develop
  volumes:
  - ${BCX_DIR}/sites-enabled:/etc/nginx/sites-enabled
  - ${BCX_DIR}/www:/var/www
  - ${BCX_DIR}/logs:/var/log/nginx
  stdin_open: true
Mongo:
  tty: true
  image: mongo:3
  volumes:
  - ${BCX_DIR}/mongo:/data/db
  stdin_open: true
